[build]
  command = "npm run build"
  publish = "_site"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/micropub"
  to = "/.netlify/functions/micropub"
  status = 200

[[redirects]]
  from = "/micropub/media"
  to = "/.netlify/functions/micropub-media"
  status = 200

[template]
  incoming-hooks = ["Ghost"]
