[build]
  command = "bash scripts/netlify-build.sh"
  publish = "_site"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/micropub"
  to = "/.netlify/functions/micropub"
  status = 200

[[redirects]]
  from = "/micropub/media"
  to = "/.netlify/functions/micropub-media"
  status = 200

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/indieauth-auth"
  status = 200

[[redirects]]
  from = "/token"
  to = "/.netlify/functions/indieauth-token"
  status = 200

[template]
  incoming-hooks = ["Ghost"]
